name: store_go
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^6.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.9.0
  intl: ^0.17.0
#  intl_translation: ^0.17.10+1
  http: ^0.13.0
  http_parser: ^4.0.0
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  flutter_switch: ^0.2.2
  image_picker: ^0.7.2
  infinite_scroll_pagination: ^3.0.1
#  dio: ^3.0.10
  toast: ^0.1.5
  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - languages/ar.json
    - languages/en.json

  fonts:
    - family: ArabicUiDisplay
      fonts:
        - asset: fonts/ArabicUIDisplay-Black.otf
          weight: 900
        - asset: fonts/ArabicUIDisplay-Bold.otf
          weight: 700
        - asset: fonts/ArabicUIDisplay-Heavy.otf
          weight: 800
        - asset: fonts/ArabicUIDisplay-Light.otf
          weight: 300
        - asset: fonts/ArabicUIDisplay-Medium.otf
          weight: 500
        - asset: fonts/ArabicUIDisplay-Regular.otf
          weight: 400
        - asset: fonts/ArabicUIDisplay-Semibold.otf
          weight: 600
        - asset: fonts/ArabicUIDisplay-Thin.otf
          weight: 100
        - asset: fonts/ArabicUIDisplay-Ultralight.otf
          weight: 200
