name: store_go
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  splashscreen:
  flutter_launcher_icons:
  intl:
  http:
  http_parser:
  bloc:
  flutter_bloc:
  flutter_switch:
  image_picker:
  toast:
  easy_localization:
  file_picker:
  dio:
  path:
  path_provider:
  mime:
  syncfusion_flutter_pdfviewer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - languages/ar.json
    - languages/en.json

  fonts:
    - family: ArabicUiDisplay
      fonts:
        - asset: fonts/ArabicUIDisplay-Black.otf
          weight: 900
        - asset: fonts/ArabicUIDisplay-Bold.otf
          weight: 700
        - asset: fonts/ArabicUIDisplay-Heavy.otf
          weight: 800
        - asset: fonts/ArabicUIDisplay-Light.otf
          weight: 300
        - asset: fonts/ArabicUIDisplay-Medium.otf
          weight: 500
        - asset: fonts/ArabicUIDisplay-Regular.otf
          weight: 400
        - asset: fonts/ArabicUIDisplay-Semibold.otf
          weight: 600
        - asset: fonts/ArabicUIDisplay-Thin.otf
          weight: 100
        - asset: fonts/ArabicUIDisplay-Ultralight.otf
          weight: 200
